name: Toplike

on:
  workflow_dispatch:

jobs:
  laravel-ngrok:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_pgsql
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Set environment variables
        # run: |
        #   echo "DB_CONNECTION=pgsql" >> .env
        #   echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        #   echo "DB_PORT=5432" >> .env
        #   echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        #   echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        #   echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        #   echo "APP_URL=http://127.0.0.1:8000" >> .env

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate App Key
        run: php artisan key:generate

      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Start Laravel + Ngrok Tunnel
        run: |
          nohup php artisan serve --host=0.0.0.0 --port=8000 > laravel.log 2>&1 &
          sleep 5
          ngrok config add-authtoken ${{ secrets.2kaphSlfriqYhFNzsSqowNZthIK_6qY4Xb5pBKhKpVfKXhcxE }}
          nohup ngrok http 8000 > ngrok.log 2>&1 &
          sleep 10

      - name: Show Ngrok Public URL
        run: curl http://127.0.0.1:4040/api/tunnels
